### ISSUE TITLE
Issue setting up a META

### ISSUE THREAD

**Issue by trebmuh** [dokufreaks/plugin-meta#4]
What I'm trying to achieve is to set up (a bunch of) pages with some tags, and then have another page listing all the pages containing one tag.

For that, I'm using the plugins TAG ([https://www.dokuwiki.org/plugin:tag]), PAGELIST ([https://www.dokuwiki.org/plugin:pagelist]) and META ([https://www.dokuwiki.org/plugin:meta]).

The plugin META is used in the hope to get exactly what I want (not the 200 or something first characters of a given page) in the list.
So I did put this META : `~~META:description abstract=blablabla - exactly what I want to be displayed in the Description field of the list - blablabla.~~`
But the list still doesn't show my "description" field in the list.

I did play around that a bit for the last 2 days and found a workaround consisting of using another plugin : METAEDITOR ([https://www.dokuwiki.org/plugin:metaeditor]). The trick is to create a persistent key : description -> abstract (and leave it empty)
Then, The description field is shown as expected.

So the good thing is : that works as a workaround \o/
An the less-good thing is : that works as a workaround ... meaning that I would need to create this empty key for every page (hundreds of them) :/

Any help would be much more appreciated.

**Comment by michitux** [comment]
Could you please test if this works now with the current version of the plugin that I've just released?

**Comment by trebmuh** [comment]
I tested with removing the persistent key and even removing the metaeditor plugin. And it does work perfectly. Thanks for your patch !
