### ISSUE TITLE
meta plugin does not set metadata as expected

### ISSUE THREAD

**Issue by tmo26** [dokufreaks/plugin-meta#5]
Dokuwiki Release 2018-04-22a "Greebo"
meta plugin Installed version: 2015-07-24

**Issue:** meta plugin does not set metadata as expected

**Example:** https://openwrt.org/toh/views/toh_dev_arch-target-cpu

**pagesource:**
```
~~META:
name="robots"
&content="noindex,nofollow"
~~
```
**html:**
`<meta name="robots" content="index,follow"/>`

-> The metadata added to the page does not have any effect on the html.

Am I using the plugin incorrectly or is this a bug?

**Comment by Klap-in** [comment]
This plugin sets or modifies the metadata which DokuWiki stores internally per wikipage. So this is not about the html meta headers in the head section of the html. 

(btw: At first glance, there are other plugins available for DokuWiki which could provide some possibilities for changing these headers)
